package com.tobiask.model

enum class States {
    MEASURING,
    WATERING,
    MEASURING_AFTER_WATERING //FIRST TEN MINUTES AFTER WATERING THIS STATE IS SET TO GIVE THE WATER TIME TO SPREAD OUT AND PREVENT A CONSTANT WATERING
}